version: "3.8"

services:
  api:
    build: ./api
    ports: 
      - 3000:3000 
    environment:
      MYSQL_HOST: ${MYSQL_HOST}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
    volumes:
      - ./api/src:/usr/app/api/src

  react-ui:
    build: ./react-frontend
    ports:
      - "3001:3001"
    container_name: react-ui
    stdin_open: true
    volumes:
       - ./react-frontend/src:/usr/app/react-frontend/src
       - ./react-frontend/src:/usr/app/react-frontend/node_modules

  db: 
    image: mysql
    restart: always
    environment: 
       MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
       MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - 3306:3306
      
  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: ${MYSQL_HOST}

  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock